[FEAT] Finish Login Page
Master-Trolls-of-IT/PLIC-front-mobile pull request #5
Opened 2023-04-04 17:01 UTC by Uzayur

Ajouts des composants génériques de custom font, de boutons, d'input et de message d'erreur. La login Page est désormais terminée.

2023-04-04 19:12 UTC, AkaMirai9 requested changes

2023-04-04 19:12 UTC, AkaMirai9 commented on src/infrastructure/ui/shared/helper/validator.ts
> +        stringRegex = '^\\w+([\\.-]?\\w+)*@\\w+([\\.-]?\\w+)*(\\.\\w{2,3})+$';
Pour la regex peut-être plutôt essayer celle ci :  [^@ \t\r\n]+@[^@ \t\r\n]+\.[^@ \t\r\n]+

2023-04-04 21:48 UTC, Uzayur commented on src/infrastructure/ui/shared/helper/validator.ts
> +        stringRegex = '^\\w+([\\.-]?\\w+)*@\\w+([\\.-]?\\w+)*(\\.\\w{2,3})+$';
bah en vrai nan

2023-04-04 21:48 UTC, Uzayur commented on src/infrastructure/ui/shared/helper/validator.ts
> +        stringRegex = '^\\w+([\\.-]?\\w+)*@\\w+([\\.-]?\\w+)*(\\.\\w{2,3})+$';
Elle est bien la string je l'ai testé sur  exemples tout passait bien

2023-04-04 21:52 UTC, Uzayur commented on src/application/utils/font/custom-font-inter-bold.ts
>      useEffect(() => {
C'est un peu sombre. J'ai essayé de le trafiquer mais ça faisait sauter la police directement. Je t'avouerai que je ne sais pas du tout comment le rétrécir (j'ai déjà perdu trop de temps dessus)

2023-04-05 07:57 UTC, AkaMirai9 approved these changes

2023-04-05 07:59 UTC, merged