Started building sign up page
Master-Trolls-of-IT/PLIC-front-mobile pull request #7
Opened 2023-04-07 18:40 UTC by lesageduvillage

2023-04-07 19:16 UTC, Uzayur commented on src/application/type/enum/input-type-enum.ts
>  }
La faudrait plutot faire un type number pour la size / weight et sportactivity. Le genre c'est pas un input en soit, c'est un choix dans une liste (doncpas un genericinput) mais faut voir comment l'implémenter. Et le Name c'est justement le champ text (pas de vérification sur l'input)

2023-04-07 19:16 UTC, Uzayur commented on src/infrastructure/ui/pages/home-page/home-page.tsx
>      );
Tu peux carrément roolback tes changes sur ce file t'es pas censé le toucher (et tu modifies rien en plus)

2023-04-07 19:16 UTC, Uzayur commented on src/infrastructure/ui/pages/sign-up-page/component/background/tree-sign-up-classic-logo.tsx
> +
peut etre juste le wording du nom de fichier, pas préciser le nom de la page (tree-invisble-logo) par ex

2023-04-07 19:16 UTC, Uzayur commented on src/infrastructure/ui/pages/sign-up-page/hooks.tsx
> +export default useSignUpPageData;
ici le genre du coup pas besoin de lui mettre un state comme on doit aps pouvoir ecrire

2023-04-07 19:16 UTC, Uzayur commented on src/infrastructure/ui/pages/sign-up-page/hooks.tsx
> +    };
Du coup ici ya bcp plus de champs a verifier, pas que l'email et le password (je pense t'as juste copy paste sans faire attention)

2023-04-07 19:16 UTC, Uzayur commented on src/infrastructure/ui/pages/sign-up-page/hooks.tsx
> +    };
Je comprends rien au bouton que t'as mis la

2023-04-07 19:16 UTC, Uzayur commented on src/infrastructure/ui/pages/sign-up-page/sign-up-page-style.ts
> +    input: {
ici ya un espace entre deux blocs de css c'est mieux pour lire

2023-04-07 19:16 UTC, Uzayur commented on src/infrastructure/ui/pages/sign-up-page/sign-up-page.tsx
> +                <Text style={{...SignUpPageStyle.text, ...CustomFontInterBold().text}}>Sign-up Page</Text>
Pourquoi le garder ca?

2023-04-07 19:16 UTC, Uzayur commented on src/infrastructure/ui/pages/sign-up-page/sign-up-page.tsx
> +                </View>
Ah mais t'as fait qu'un seul input en fait xD

2023-04-07 19:16 UTC, Uzayur commented on src/infrastructure/ui/shared/component/generic-dropdown/generic-dropdown.tsx
> +export default GenericDropDown;
ca j'imagine que c'est pas fini donc je regarde pas

2023-04-07 19:16 UTC, Uzayur commented on src/infrastructure/ui/shared/component/generic-header-text/generic-header-text-style.ts
> +        fontSize: 27 * (Dimensions.get('screen').height / 725)
Tu l'as beaucoup baissé la, oblige de descendre si bas ?

2023-04-07 19:52 UTC, lesageduvillage commented on src/infrastructure/ui/pages/sign-up-page/hooks.tsx
> +    };
oui oui la j'ai juste repris le code de l'inscription
mais je vais le remplir dans le futur

2023-04-07 20:09 UTC, lesageduvillage commented on src/infrastructure/ui/pages/sign-up-page/sign-up-page.tsx
> +                </View>
oui mdrrrr

2023-04-07 20:10 UTC, lesageduvillage commented on src/infrastructure/ui/shared/component/generic-header-text/generic-header-text-style.ts
> +        fontSize: 27 * (Dimensions.get('screen').height / 725)
bah sur mon tel j'ai mis la font la plus grande possible pour que ca rentre en une ligne

2023-04-09 10:09 UTC, AkaMirai9 requested changes

2023-04-09 10:09 UTC, AkaMirai9 commented on src/application/type/enum/input-type-enum.ts
> +    Genre = 'genre',
Pour rester dans la logique d'avoir l'enum en anglais : 
```suggestion
    Gender = 'gender',
```

2023-04-09 10:09 UTC, AkaMirai9 commented on src/infrastructure/ui/pages/home-page/home-page.tsx
> +const HomePage: FunctionComponent<unknown> = () => {
Ici le 
```
const HomePage: FunctionComponent<any> = ({ navigation }) => {
```
est obligatoire pour la suite, on sait que le linter n'aime pas mais mais sans la props navigation il est impossible de changer de page

2023-04-09 10:09 UTC, AkaMirai9 commented on src/infrastructure/ui/pages/sign-up-page/hooks.tsx
> +    };
Oui du coup il faudrait ajouter des types dans isValidateInput et modifier le onPress Login

2023-04-12 10:56 UTC, lesageduvillage commented on src/application/utils/regex/date.ts
Un regex vreuuuuuument

2023-04-12 17:52 UTC, Uzayur commented on src/application/type/props/input-with-end-text-props.ts
> +export type InputWithEndTextProps = {
Plutôt renommer en GenericInputWithEndText nan ? (je parle du composant global pas uniquement de ce type)

2023-04-12 17:52 UTC, Uzayur commented on src/infrastructure/ui/hooks.ts
> +        // Hide it
Renomme juste la fonction en mode hideNavigationBar je pense que ce sera plus explicite (plus besoin du com comme ca)

2023-04-12 17:52 UTC, Uzayur commented on src/infrastructure/ui/pages/sign-up-page/hooks.tsx
> +export default useSignUpPageData;
Si j'ai bien compris ici on le fera plus tard c'es ça ?

2023-04-12 17:52 UTC, Uzayur commented on src/infrastructure/ui/pages/sign-up-page/sign-up-page-style.ts
> +
Pas ouf les wording ici pour les classes css

2023-04-12 17:52 UTC, Uzayur commented on src/infrastructure/ui/pages/sign-up-page/sign-up-page.tsx
> +                            placeHolder={'176'}
Je pinaille un peu mais c'est kg et pas Kg (pareil pour Cm et cm)

2023-04-12 17:52 UTC, Uzayur commented on src/infrastructure/ui/pages/sign-up-page/sign-up-page.tsx
> +                            style={{ flex: 1.2 }}
C'est mieux de mettre le style dans le fichier style nan ?

2023-04-12 17:52 UTC, Uzayur commented on src/infrastructure/ui/shared/component/generic-dropdown/generic-dropdown-style.tsx
> +    // Make the container fill the remaining space
Commentaire useless c'est explicite

2023-04-12 17:52 UTC, Uzayur commented on src/infrastructure/ui/shared/component/generic-dropdown/generic-dropdown-style.tsx
> +});
On met pas de retour à la ligne entre chaque classes ici ? C'est moins lisible comme ça je trouve

2023-04-12 17:52 UTC, Uzayur commented on src/infrastructure/ui/shared/component/generic-dropdown/generic-dropdown.tsx
> +
Dead code

2023-04-12 17:52 UTC, Uzayur commented on src/infrastructure/ui/shared/component/generic-dropdown/generic-dropdown.tsx
> +    const { selected, toggleDropdown, renderDropdown, DropdownButton } = useGenericDropDownData(() => {}, options);
Autant mettre l'argument fonction en optionnel et lui donner une default value

2023-04-12 17:52 UTC, Uzayur commented on src/infrastructure/ui/shared/component/generic-dropdown/generic-dropdown.tsx
> +                    {(!!selected && selected.label) || options[0].label}
Le !! est vraiment laid ici, je sais ce que t'as voulu faire mais normalement juste selected fonctionne en mettant selected?.label

2023-04-12 17:52 UTC, Uzayur commented on src/infrastructure/ui/shared/component/generic-dropdown/generic-dropdown.tsx
> +                        asset={require('~/domain/entities/assets/icon/icon-drop-down.svg')}
Je truove ca plus sexy de mettre le require dans une constante ca fait moinbs lourd

2023-04-12 17:52 UTC, Uzayur commented on src/infrastructure/ui/shared/component/generic-dropdown/hooks.tsx
> +const useGenericDropDownData = (
Espace entre les imports et la fonction

2023-04-12 17:52 UTC, Uzayur commented on src/infrastructure/ui/shared/component/generic-dropdown/hooks.tsx
> +        // @ts-ignore
OH NAN SACRILEGE

2023-04-12 17:52 UTC, Uzayur commented on src/infrastructure/ui/shared/component/generic-dropdown/hooks.tsx
> +        DropdownButton.current.measure((_fx: number, _fy: number, w: number, h: number, px: number, py: number) => {
Les noms sont atroces mdrrr

2023-04-12 17:52 UTC, Uzayur commented on src/infrastructure/ui/shared/component/generic-dropdown/hooks.tsx
> +                        <FlatList
Pareil pour le style ici je pense qe c'est mieux de le mettre dnas un fichier style

2023-04-12 17:52 UTC, Uzayur commented on src/infrastructure/ui/shared/component/generic-input/generic-input-style.ts
> +        // width: 360 * (Dimensions.get('screen').width / 400),
Dead Code et je comprends pas pourquoi l'enlever ?

2023-04-12 17:52 UTC, Uzayur commented on src/infrastructure/ui/shared/component/generic-input/generic-input.tsx
> +                    value={input}
Ca fait quoi concrètement ?

2023-04-12 17:52 UTC, Uzayur commented on src/infrastructure/ui/shared/component/generique-birthdate/generic-birthdate.tsx
> +const GenericBirthdate = ({ title, input, dispatch, style, placeHolder }: GenericBirthdateProps) => {
GenericInputBirthdate serat mieux nan ?

2023-04-12 17:52 UTC, Uzayur commented on src/infrastructure/ui/shared/component/generique-birthdate/hooks.ts
> +    const onChange = (value: string) => {
Espace wesh

2023-04-12 17:52 UTC, Uzayur commented on src/infrastructure/ui/shared/component/generique-birthdate/hooks.ts
> +            }
Le isNan(parseInt()) tu l'utilises beaucoup jepenses que ça serait nan de juste en faire une autre fonction plus claire que t'appellerais ici (en faire un utils)

2023-04-12 17:52 UTC, Uzayur commented on src/infrastructure/ui/shared/component/input-with-end-text/hooks.ts
> +            if (isNaN(parseInt(value))) return prev;
Same ici. En plus je trouve que isNan(parseInt()) est vrament moche

2023-04-12 17:52 UTC, Uzayur commented on src/infrastructure/ui/shared/component/input-with-end-text/input-with-end-text-style.ts
> +        // width: 360 * (Dimensions.get('screen').width / 400),
Pourquoi l'enlever ? Tu la gères ou la weight ?

2023-04-13 07:13 UTC, AkaMirai9 commented on src/application/type/props/input-with-end-text-props.ts
> +export type InputWithEndTextProps = {
done

2023-04-13 07:49 UTC, AkaMirai9 approved these changes

2023-04-13 08:04 UTC, merged